keys:
  - &prince213 E0645733CAF3765161044422FF1953A2BDC72EB8
  - &pegasus age10u4x9074jjv2tvwfryt9lpf4wcdtcktv9zwfxspht8yzvcsz0arsqt0t9h
creation_rules:
  - path_regex: systems/pegasus/secrets.yaml
    key_groups:
      - age:
          - *pegasus
        pgp:
          - *prince213
  - path_regex: secrets.yaml
    key_groups:
      - pgp:
          - *prince213
stores:
  yaml:
    indent: 2
